# Generated by Django 5.2.15 on 2026-06-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chapterfile_course_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='assignment_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chapter',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
