# Generated by Django 5.2.15 on 2026-06-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterfile',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_files/previews/'),
        ),
    ]
